Website_Plant/Pages/Admin/Message/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Website_Plant.MyHelpers;

namespace Website_Plant.Pages.Admin.Message
{
    [RequireAuth(RequiredRole = "admin")]
    public class DetailModel : PageModel
    {
        public Contact contact = new Contact();

        public void OnGet()
        {
            string requestId = Request.Query["id"];
            try
            {
                string connectionString = "Data Source=Localhost\\sqlexpress;Initial Catalog=WebPlant;Integrated Security=True;Encrypt=True;Trust Server Certificate=True";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    string sql = "SELECT * FROM Contact where id=@id";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@id", requestId);
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.Read())
                            {
                                contact.ID = reader.GetInt32(0);
                                contact.FullName = reader.GetString(1);
                                contact.PhoneNumber = reader.GetString(2);
                                contact.Email = reader.GetString(3);
                                contact.Message = reader.GetString(4);
                                contact.CreatedAt = reader.GetDateTime(5).ToString("dd/MM/yyyy");
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Response.Redirect("Admin/Message/Index");
            }
        }
    }
}

Website_Plant/Pages/Admin/Order/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Website_Plant.MyHelpers;

namespace Website_Plant.Pages.Admin.Order
{
    [RequireAuth(RequiredRole = "admin")]
    public class DetailModel : PageModel
    {
        public OrderInfo orderInfo = new OrderInfo();
        public UserInfo userInfo = new UserInfo();
        public void OnGet(int id)
        {
            if (id < 1)
            {
                Response.Redirect("/Admin/Order/Index");
                return;
            }
            string orderStatus = Request.Query["order_status"];

            try
            {
                string connectionString = "Data Source=Localhost\\sqlexpress;Initial Catalog=WebPlant;Integrated Security=True;Encrypt=True;Trust Server Certificate=True";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    if (orderStatus != null)
                    {
                        string sqlUpdate = "update orders set order_status=@order_status where id=@id";
                        using (SqlCommand command = new SqlCommand(sqlUpdate, connection))
                        {
                            command.Parameters.AddWithValue("@order_status", orderStatus);
                            command.Parameters.AddWithValue("@id", id);
                            command.ExecuteNonQuery();
                        }
                    }

                    string sql = "select * from orders where id=@id";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@id", id);
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.Read())
                            {
                                orderInfo.id = reader.GetInt32(0);
                                orderInfo.clientId = reader.GetInt32(1);
                                orderInfo.orderDate = reader.GetDateTime(2).ToString("dd/MM/yyyy");
                                orderInfo.shippingFee = reader.GetDecimal(3);
                                orderInfo.deliveryAddress = reader.GetString(4);
                                orderInfo.paymentMethod = reader.GetString(5);
                                orderInfo.orderStatus = reader.GetString(6);

                                orderInfo.items = OrderInfo.getOrderItems(orderInfo.id);
                            }
                            else
                            {
                                Response.Redirect("/Admin/Order/Index");
                                return;
                            }
                        }
                    }
                    sql = "select * from users where id=@id";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@id", orderInfo.clientId);
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.Read())
                            {
                                userInfo.id = reader.GetInt32(0);
                                userInfo.fullName = reader.GetString(1);
                                userInfo.email = reader.GetString(2);
                                userInfo.phone = reader.GetString(3);
                                userInfo.address = reader.GetString(4);
                                userInfo.password = reader.GetString(5);
                                userInfo.role = reader.GetString(6);
                                userInfo.created_at = reader.GetDateTime(7).ToString("dd/MM/yyyy");

                            }
                            else
                            {
                                Console.WriteLine("Không tìm thấy khách hàng có mã=" + orderInfo.clientId);
                                Response.Redirect("/Admin/Order/Index");
                                return;
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Response.Redirect("/Admin/Order/Index");
            }
        }
    }
    public class UserInfo
    {
        public int id;
        public string fullName;
        public string email;
        public string phone;
        public string address;
        public string password;
        public string role;
        public string created_at;
    }
}

Website_Plant/Pages/CheckoutVnpay.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;
using System.Net.Sockets;
using System.Net;
using Website_Plant.MyHelpers;

namespace Website_Plant.Pages
{
    public class CheckoutVnpayModel : PageModel
    {
        public string DeliveryAddress { get; set; } = "";
        public string Total { get; set; } = "";
        public string ProductIdentifiers { get; set; } = "";
        public void OnGet()
        {
            DeliveryAddress = TempData["DeliveryAddress"]?.ToString() ?? "";
            Total = TempData["Total"]?.ToString() ?? "";
            ProductIdentifiers = TempData["ProductIdentifiers"]?.ToString() ?? "";

            TempData.Keep(); // Giữ lại dữ liệu TempData khi tải lại trang
            if (DeliveryAddress == "" || Total == "" || ProductIdentifiers == "")
            {
                Console.WriteLine($"Total: {Total}, DeliveryAddress: {DeliveryAddress}, ProductIdentifiers: {ProductIdentifiers}");
                Response.Redirect("/");
                return;
            }
            Console.WriteLine($"Total: {Total}, DeliveryAddress: {DeliveryAddress}, ProductIdentifiers: {ProductIdentifiers}");

        }
        public void OnPostRedirectToVnpay()
        {
            DeliveryAddress = TempData["DeliveryAddress"]?.ToString() ?? "";
            Total = TempData["Total"]?.ToString() ?? "";
            ProductIdentifiers = TempData["ProductIdentifiers"]?.ToString() ?? "";

            TempData.Keep(); // Giữ lại dữ liệu TempData khi tải lại trang
            if (DeliveryAddress == "" || Total == "" || ProductIdentifiers == "")
            {
                Console.WriteLine($"Total: {Total}, DeliveryAddress: {DeliveryAddress}, ProductIdentifiers: {ProductIdentifiers}");
                Response.Redirect("/");
                return;
            }
            // Cấu hình thông tin VNPay
            string vnp_Returnurl = "http://localhost:5237/thankyou"; // URL nhận kết quả từ VNPay
            string vnp_Url = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"; // URL thanh toán VNPay
            string vnp_TmnCode = "JH6ZQB6C"; // Mã website của bạn
            string vnp_HashSecret = "CEVA3S04FEYIX7P466RXHJHKE37JAWDG"; // Chuỗi bí mật của bạn

            // Kiểm tra và xử lý giá trị Total
            if (string.IsNullOrEmpty(Total))
            {
                throw new Exception("Giá trị Total không được truyền hoặc rỗng.");
            }

            // Loại bỏ các ký tự không hợp lệ nếu cần
            string cleanedTotal = new string(Total.Where(char.IsDigit).ToArray());

            if (!decimal.TryParse(cleanedTotal, NumberStyles.Any, CultureInfo.InvariantCulture, out decimal totalDecimal))
            {
                throw new Exception($"Giá trị Total không hợp lệ: {Total}");
            }

            // Chuyển đổi Total sang đơn vị VNPay yêu cầu (VNĐ x 100)
            string totalAmount = (totalDecimal * 100).ToString("0");

            VnPayLibrary vnpay = new VnPayLibrary();
            vnpay.AddRequestData("vnp_Version", "2.1.0");
            vnpay.AddRequestData("vnp_Command", "pay");
            vnpay.AddRequestData("vnp_TmnCode", vnp_TmnCode);
            vnpay.AddRequestData("vnp_Amount", totalAmount);
            vnpay.AddRequestData("vnp_CreateDate", DateTime.Now.ToString("yyyyMMddHHmmss"));
            vnpay.AddRequestData("vnp_CurrCode", "VND");
            vnpay.AddRequestData("vnp_IpAddr", GetIpAddress(HttpContext));
            vnpay.AddRequestData("vnp_Locale", "vn");
            vnpay.AddRequestData("vnp_OrderInfo", "Don hang mua tu web plant");
            vnpay.AddRequestData("vnp_OrderType", "other");

            vnpay.AddRequestData("vnp_ReturnUrl", vnp_Returnurl);
            vnpay.AddRequestData("vnp_TxnRef", DateTime.Now.Ticks.ToString()); // Mã tham chiếu giao dịch

            string paymentUrl = vnpay.CreateRequestUrl(vnp_Url, vnp_HashSecret);

            // Chuyển hướng đến VNPay
            Response.Redirect(paymentUrl);
        }
        public static string GetIpAddress(HttpContext context)
        {
            var ipAddress = string.Empty;
            try
            {
                var remoteIpAddress = context.Connection.RemoteIpAddress;

                if (remoteIpAddress != null)
                {
                    if (remoteIpAddress.AddressFamily == AddressFamily.InterNetworkV6)
                    {
                        remoteIpAddress = Dns.GetHostEntry(remoteIpAddress).AddressList
                            .FirstOrDefault(x => x.AddressFamily == AddressFamily.InterNetwork);
                    }

                    if (remoteIpAddress != null) ipAddress = remoteIpAddress.ToString();
                    return ipAddress;
                }
            }
            catch (Exception ex)
            {
                return "Invalid IP:" + ex.Message;
            }

            return "127.0.0.1";
        }
    }
}

Website_Plant/Pages/Client/Order/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Website_Plant.MyHelpers;
using Website_Plant.Pages.Admin.Order;

namespace Website_Plant.Pages.Client.Order
{
    [RequireAuth(RequiredRole = "client")]
    public class DetailModel : PageModel
    {
        public OrderInfo orderInfo = new OrderInfo();
        public void OnGet(int id)
        {
            int clientId = HttpContext.Session.GetInt32("id") ?? 0;
            if (id < 1)
            {
                Response.Redirect("/Client/Order/Index");
                return;
            }


            try
            {
                string connectionString = "Data Source=Localhost\\sqlexpress;Initial Catalog=WebPlant;Integrated Security=True;Encrypt=True;Trust Server Certificate=True";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();



                    string sql = "select * from orders where id=@id and client_id=@client_id";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@id", id);
                        command.Parameters.AddWithValue("@client_id", clientId);
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.Read())
                            {
                                orderInfo.id = reader.GetInt32(0);
                                orderInfo.clientId = reader.GetInt32(1);
                                orderInfo.orderDate = reader.GetDateTime(2).ToString("dd/MM/yyyy");
                                orderInfo.shippingFee = reader.GetDecimal(3);
                                orderInfo.deliveryAddress = reader.GetString(4);
                                orderInfo.paymentMethod = reader.GetString(5);
                                orderInfo.orderStatus = reader.GetString(6);

                                orderInfo.items = OrderInfo.getOrderItems(orderInfo.id);
                            }
                            else
                            {
                                Response.Redirect("/Client/Order/Index");
                                return;
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Response.Redirect("/Client/Order/Index");
            }
        }
    }
}

Website_Plant/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Website_Plant.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Website_Plant/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Website_Plant.Pages.Admin.Plant;

namespace Website_Plant.Pages
{
    public class IndexModel : PageModel
    {
        public List<PlantInfo> listNewestPlants = new List<PlantInfo>();
        public List<PlantInfo> listTopSales = new List<PlantInfo>();

        public void OnGet()
        {
			try
			{
				string connectionString = "Data Source=Localhost\\sqlexpress;Initial Catalog=WebPlant;Integrated Security=True;Encrypt=True;Trust Server Certificate=True";
				using (SqlConnection connection = new SqlConnection(connectionString))
				{
					connection.Open();
					string sql = "select top 5 * from plants order by ngaytao desc";
					using (SqlCommand command = new SqlCommand(sql, connection))
					{
						using (SqlDataReader reader = command.ExecuteReader())
						{
							while (reader.Read())
							{
								PlantInfo plantInfo = new PlantInfo();
								plantInfo.Id = reader.GetInt32(0);
								plantInfo.tensp = reader.GetString(1);
								plantInfo.mota = reader.GetString(2);
								plantInfo.anhsang = reader.GetString(3);
								plantInfo.tuoinuoc = reader.GetString(4);
								plantInfo.nhietdo = reader.GetString(5);
								plantInfo.danhmuc = reader.GetString(6);
								plantInfo.gia = reader.GetDecimal(7);
								plantInfo.ImageFileName = reader.GetString(8);
								plantInfo.ngaytao = reader.GetDateTime(9).ToString("dd/MM/yyyy");
								listNewestPlants.Add(plantInfo);
							}
						}
					}

					sql = "select top 5 plants.*, (" +
						"select sum(order_items.quantity) from order_items where plants.id = order_items.plant_id" +
						") as total_sales " +
						"from plants " +
						"order by total_sales desc";
					using (SqlCommand command = new SqlCommand(sql, connection))
					{
						using (SqlDataReader reader = command.ExecuteReader())
						{
							while (reader.Read())
							{
								PlantInfo plantInfo = new PlantInfo();
								plantInfo.Id = reader.GetInt32(0);
								plantInfo.tensp = reader.GetString(1);
								plantInfo.mota = reader.GetString(2);
								plantInfo.anhsang = reader.GetString(3);
								plantInfo.tuoinuoc = reader.GetString(4);
								plantInfo.nhietdo = reader.GetString(5);
								plantInfo.danhmuc = reader.GetString(6);
								plantInfo.gia = reader.GetDecimal(7);
								plantInfo.ImageFileName = reader.GetString(8);
								plantInfo.ngaytao = reader.GetDateTime(9).ToString("dd/MM/yyyy");
								listTopSales.Add(plantInfo);
							}
						}
					}
				}
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex.Message);
			}
		}
    }
}

Website_Plant/Pages/Cart.cshtml
@page
@using System.Globalization
@model CartModel
@section Styles {
    <link rel="stylesheet" href="~/css/Cart.css" />
}
@{
    ViewData["NoContainer"] = true;
}

<body>
    <div class="cart-container">
        <div class="Tieude">
            <h1>Giỏ hàng</h1>
            @if (Model.errorMessage.Length > 0)
            {
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>@Model.errorMessage</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            else if (Model.successMessage.Length > 0)
            {
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>@Model.successMessage</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
        </div>
        <div class="cart">
            <div class="cart-items">
                <table>
                    <tr>
                        <th>Sản phẩm</th>
                        <th></th>
                        <th>Số lượng</th>
                        <th>Tổng</th>
                        <th></th>
                    </tr>
                    @foreach(var item in Model.listOrderItem)
                    {
                        <tr>
                            <td><img src="/image/plants/@item.plantInfo.ImageFileName" alt="Ảnh sản phẩm"></td>
                            <td>
                                <p style="font-weight:500;  font-size:20px;">@item.plantInfo.tensp</p>
                                <p style="color: #757575;">@(item.plantInfo.gia.ToString("N0", new CultureInfo("vi-VN"))) đ</p>
                            </td>
                            <td>
                                <a role="button" class="table-link" href="/cart?action=sub&id=@(item.plantInfo.Id)">-</a>
                                <span style="font-weight: 500;">@item.numCopies</span>
                                <a role="button" class="table-link" href="/cart?action=add&id=@(item.plantInfo.Id)">+</a>
                            </td>
                            <td><p1>@(item.totalPrice.ToString("N0", new CultureInfo("vi-VN"))) đ</p1></td>
                            <td><a class="table-link" href="/cart?action=delete&id=@(item.plantInfo.Id)" onclick="return confirm('Bạn có chắc chắn muốn xóa sản phẩm này khỏi giỏ hàng?')" ><i class="bi bi-trash"></i>

                        </a>

                        </td>
                        </tr>
                    }                   
                </table>
              </div>
            <div class="cart-summary">
                @if (HttpContext.Session.GetString("role") == null)
                {
                    <div class="summary-details">
                        <p>Tổng đơn hàng: <span style="font-weight:400;">@(Model.totalproduct.ToString("N0", new CultureInfo("vi-VN"))) đ</span></p>
                    </div>
                    <hr style="color: #1F3505;" />
                    <div class="text-notify">
                        <p>Hãy đăng nhập để đặt hàng. Nếu chưa có tài khoản hãy đăng ký.</p>
                    </div>
                    <div class="auth-signinup">
                        <a class="link-btn-signin" href="/Auth/signin" role="button">Đăng nhập</a>
                        <a class="link-btn-signup" href="/Auth/signup" role="button">Đăng ký</a>
                    </div>
                }
                else
                {
                    <form method="post">
                        <h2>Địa chỉ giao hàng</h2>
                        <input type="text" asp-for="Address">
                        <span class="text-danger" asp-validation-for="Address"></span>
                        <h2>Chọn phương thức thanh toán</h2>
                        <select asp-for="PaymentMethod">
                            <option value="cod">COD</option>
                            <option value="vnpay">VnPay</option>
                        </select>

                        <div class="summary-details">
                            <p>Tổng đơn hàng: <span style="font-weight:400;">@(Model.totalproduct.ToString("N0", new CultureInfo("vi-VN"))) đ</span></p>
                            <p>Phí vận chuyển: <span style="font-weight:400;">@(Model.shippingfee.ToString("N0", new CultureInfo("vi-VN"))) đ</span></p>
                            <p>Tổng thanh toán: <span style="font-weight:400;">@(Model.total.ToString("N0", new CultureInfo("vi-VN"))) đ</span></p>
                        </div>
                        <button class="checkout-btn" type="submit">Thanh toán</button>
                    </form>
                }               
            </div>
        </div>
    </div>
</body>

Website_Plant/Pages/CheckoutVnpay.cshtml
@page
@using System.Globalization
@model Website_Plant.Pages.CheckoutVnpayModel
@{
}
<div class="p-5" style="background-color: #fef7ef;">
    <div class="mx-auto p-3 bg-light rounded border" style="width: 420px;">
        <h2 class="text-center mb-5">Hoàn thành thanh toán</h2>
        <div class="row mb-3">
            <div class="col-5">Địa chỉ giao hàng</div>
            <div class="col-7">@Model.DeliveryAddress</div>
        </div>
        <div class="row mb-3">
            <div class="col-5">Tổng thanh toán</div>
            <div class="col-7">@Model.Total VND</div>
        </div>
        <div class="row mb-3">
            <div class="col-5">Số lượng</div>
            <div class="col-7">@(Model.ProductIdentifiers.Split("-").Length)</div>
        </div>
        <br />
        <form method="post" asp-page-handler="RedirectToVnpay">
            <button type="submit" class="btn btn-primary" style="width: 100%;">Thanh Toán VNPay</button>
        </form>
    </div>
</div>

Website_Plant/Pages/Index.cshtml
@page
@using System.Globalization
@model IndexModel
@section Styles {
    <link rel="stylesheet" href="~/css/home.css" />
}
@{
    ViewData["Title"] = "Home Sweet Garden";
}

<body>
    <section class="hero">
        <div class="slider-wrapper">
            <div class="slider">
                <img id="slide1" src="~/image/context3.png" />
                <img id="slider2" src="~/image/context6.png" />
                <img id="slider3" src="~/image/context5.png" />
            </div>
            <div class="slider-nav">
                <a href="#slider1"></a>
                <a href="#slider2"></a>
                <a href="#slider3"></a>
            </div>
        
            <div class="hero-content">
                <h1>Explore the green world</h1>
            </div>
        </div>
    </section>

    <section class="products">
        <h2>Sản phẩm mới</h2>
        <div class="product-list">
            @foreach(var item in Model.listNewestPlants)
            {
                <div class="product-card">
                    <a href="/detail?id=@(item.Id)" role="button"><img src="/image/plants/@item.ImageFileName" alt="Ảnh cây cảnh"></a>
                    <h3>@item.tensp</h3>
                    <p>@item.gia.ToString("N0", new CultureInfo("vi-VN")) VND</p>
                </div>
            }           
        </div>
    </section>

    <section class="best-sellers">
        <h2>Sản phẩm bán chạy</h2>
        <div class="product-list">
            @foreach (var item in Model.listTopSales)
            {
                <div class="product-card">
                    <a href="/detail?id=@(item.Id)" role="button"><img src="/image/plants/@item.ImageFileName" alt="Ảnh cây cảnh"></a>
                    <h3>@item.tensp</h3>
                    <p>@item.gia.ToString("N0", new CultureInfo("vi-VN")) VND</p>
                </div>
            }
        </div>
    </section>

    <section class="aboutus">
        <div class="image">
            
        </div>

        <div class="content">
            <h2>Về chúng tôi</h2>
            <span><!-- line here --></span>

            <p>Home Sweet Garden là một trang web chuyên bán cây cảnh, mang đến không gian xanh và sự thư giãn cho mọi ngôi nhà. Trang web tập trung cung cấp đa dạng các loại cây cảnh từ cây mini để bàn, cây trồng trong nhà, đến các loại cây trang trí sân vườn. Tìm hiểu thêm hoặc liên hệ với chúng tôi.</p>

            <ul class="links">
                <li><a href="/aboutus">Tìm hiểu thêm</a></li>
                <div class="vertical-line"></div>
                <li><a href="contactus">Liên hệ</a></li>
            </ul>

            <ul class="icons">
                <li>
                    <a href="#"><i class="bi bi-facebook"></i></a>
                </li>
                <li>
                    <a href="#"><i class="bi bi-instagram"></i></a>
                </li>
                <li>
                    <a href="#"><i class="bi bi-twitter-x"></i></a>
                </li>
                
            </ul>
        </div>
    </section>

    <section class="why-choose-us">
        <h2>Vì sao nên chọn chúng tôi ?</h2>
        <div class="features">
            <div class="feature">
                <i class="bi bi-telephone"></i>
                <p>Dịch vụ 24/7</p>
            </div>
            <div class="feature">
                <i class="bi bi-truck"></i>
                <p>Vận chuyển nhanh</p>
            </div>
            <div class="feature">
                <i class="bi bi-calendar2-check"></i>
                <p>Bảo hành 5 ngày</p>
            </div>
        </div>
    </section>

    <script>
        const slider = document.querySelector('.slider');
        const navButtons = document.querySelectorAll('.slider-nav a');
        const slides = document.querySelectorAll('.slider img');

        let currentIndex = 0; 
        const slideInterval = 3000;

        // Hàm cuộn đến slide tương ứng
        function goToSlide(index) {
            const slideWidth = slider.offsetWidth;
            slider.scrollLeft = index * slideWidth;
            navButtons.forEach((btn, i) => {
                btn.style.opacity = i === index ? '1' : '0.75';
            });
            currentIndex = index;
        }

        // Hàm chuyển sang slide tiếp theo
        function nextSlide() {
            currentIndex = (currentIndex + 1) % slides.length;
            goToSlide(currentIndex);
        }

        let autoSlide = setInterval(nextSlide, slideInterval);

        // Thêm sự kiện click cho các nút điều hướng
        navButtons.forEach((button, index) => {
            button.addEventListener('click', (e) => {
                e.preventDefault(); // Ngăn hành vi mặc định của thẻ <a>
                clearInterval(autoSlide); // Dừng auto slide khi click
                goToSlide(index);
                autoSlide = setInterval(nextSlide, slideInterval); // Khởi động lại auto slide
            });
        });
    </script>

</body>

Website_Plant/Pages/contactus.cshtml
@page
@model Website_Plant.Pages.contactusModel

@section Styles {
    <link rel="stylesheet" href="~/css/contact.css" />
}

<body>
    <div class="alert-container">
        @if (Model.ErrorMessage.Length > 0)
        {
            <div class='alert alert-warning alert-dismissible fade show alert-padding alert-no-margin' role='alert'>
                <strong>@Model.ErrorMessage</strong>
                <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
            </div>
        }
        else if (Model.SuccessMessage.Length > 0)
        {
            <div class='alert alert-success alert-dismissible fade show alert-padding alert-no-margin' role='alert'>
                <strong>@Model.SuccessMessage</strong>
                <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
            </div>
        }
    </div>
    <div class="container">

        <form method="post">
            <h1>Liên hệ với chúng tôi</h1>
            <input type="text" name="fullname" id="fullname" placeholder="Họ & Tên" value="@Model.FullName" />
            

            <input type="text" name="phone" id="phone" placeholder="SĐT" value="@Model.PhoneNumber" />
            

            <input type="email" name="email" id="email" placeholder="Email" value="@Model.Email" />
            

            <textarea name="message" placeholder="Hãy viết lời nhắn ở đây nhé" value="@Model.Message"></textarea>

           
            <input type="submit" value="Gửi đi" id="button" />
        </form>
    </div>
</body>

Website_Plant/Pages/thankyou.cshtml
@page
@model Website_Plant.Pages.thankyouModel
@section Styles {
    <link rel="stylesheet" href="~/css/thankyou.css" />
}
<div class="main-content">
    <div class="card-success">
        <img src="~/image/check_success.png" width="144" height="144" />
        <h1>Đơn hàng được đặt thành công</h1>
        <div class="button-back">
            <a href="/">Về Trang chủ</a>
        </div>
    </div>
</div>